CREATE DEFINER=`root`@`localhost` PROCEDURE `add_user` (IN `id` VARCHAR(8), IN `nick` VARCHAR(100), IN `pwd` VARCHAR(20), IN `type` VARCHAR(30))  NO SQL INSERT INTO users VALUES(id, nick, pwd, type);
CREATE DEFINER=`root`@`localhost` PROCEDURE `delete_user` (IN `id` VARCHAR(10))  NO SQL DELETE FROM users WHERE id_usr=id;
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_user_type` (IN `nick` VARCHAR(100))  NO SQL SELECT type_usr FROM users WHERE nick_usr=nick;
CREATE DEFINER=`root`@`localhost` PROCEDURE `login` (IN `nick` VARCHAR(100), IN `pwd` VARCHAR(50))  NO SQL SELECT COUNT(*) FROM users WHERE nick_usr=nick AND pwd_usr=pwd;
CREATE DEFINER=`root`@`localhost` PROCEDURE `search_user` (IN `id` VARCHAR(10))  NO SQL SELECT * FROM users WHERE id_usr=id;
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_user` (IN `id` VARCHAR(10), IN `nick` VARCHAR(100), IN `pwd` VARCHAR(20))  NO SQL UPDATE users SET id_usr=id, nick_usr=nick, pwd_usr=pwd WHERE id_usr=id;
CREATE DEFINER=`root`@`localhost` PROCEDURE `carrito`() NO SQL SELECT id, producto, precio, cantidad FROM shopping_cart ORDER BY n DESC;
CREATE DEFINER=`root`@`localhost` PROCEDURE `subtotal_carrito`() NO SQL SELECT SUM(precio*cantidad) as total FROM shopping_cart;
CREATE DEFINER=`root`@`localhost` PROCEDURE `actualizarItem`(IN `cantidad_` INT(8), IN `id_` VARCHAR(10)) NO SQL UPDATE shopping_cart SET cantidad=cantidad_ WHERE id=id_;
CREATE DEFINER=`root`@`localhost` PROCEDURE `borrarItem`(IN `id_` VARCHAR(15)) NO SQL DELETE FROM shopping_cart WHERE id = id_;
CREATE DEFINER=`root`@`localhost` PROCEDURE `buscarItem`(IN `id_` VARCHAR(10)) NO SQL SELECT id, producto, precio FROM inventario WHERE id=id_;
CREATE DEFINER=`root`@`localhost` PROCEDURE `existeItem`(IN `id_` VARCHAR(10)) NO SQL SELECT COUNT(*) FROM shopping_cart WHERE id=id_;
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertarItem`(IN `id_` VARCHAR(20), IN `producto_` VARCHAR(50), IN `precio_` DOUBLE(6,2), IN `cantidad_` INT(4)) NO SQL INSERT INTO shopping_cart VALUES(id_, producto_, precio_, cantidad_, null);
CREATE DEFINER=`root`@`localhost` PROCEDURE `mostrarItems`() NO SQL SELECT * FROM inventario WHERE stock > 0;
CREATE DEFINER=`root`@`localhost` PROCEDURE `vaciarCarrito`() NO SQL TRUNCATE shopping_cart;
CREATE TABLE `inventario` (`id` varchar(20) NOT NULL, `producto` varchar(75) NOT NULL, `descripcion` varchar(125) NOT NULL, `stock` int(10) NOT NULL, `precio` double(6,2) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `shopping_cart` (`id` varchar(20) COLLATE utf8_spanish_ci NOT NULL, `producto` varchar(50) COLLATE utf8_spanish_ci NOT NULL, `precio` double(6,2) NOT NULL, `cantidad` int(4) NOT NULL, `n` int(10) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
CREATE TABLE `users` (`id_usr` varchar(10) NOT NULL, `nick_usr` varchar(100) NOT NULL, `pwd_usr` varchar(20) NOT NULL, `type_usr` varchar(30) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `ventas` (`id` varchar(10) COLLATE utf8_spanish_ci NOT NULL,`producto` varchar(50) COLLATE utf8_spanish_ci NOT NULL,`cantidad` int(100) NOT NULL, `total` double(6,2) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
INSERT INTO `users` (`id_usr`, `nick_usr`, `pwd_usr`, `type_usr`) VALUES('1', 'Administrador', '0000', 'Admin');
ALTER TABLE `inventario` ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `id` (`id`);
ALTER TABLE `shopping_cart` ADD PRIMARY KEY (`n`), ADD UNIQUE KEY `id` (`id`);
ALTER TABLE `users` ADD PRIMARY KEY (`id_usr`), ADD UNIQUE KEY `id_usr` (`id_usr`), ADD UNIQUE KEY `nick_usr` (`nick_usr`);
ALTER TABLE `ventas` ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `id` (`id`), ADD UNIQUE KEY `producto` (`producto`);
ALTER TABLE `shopping_cart` MODIFY `n` int(10) NOT NULL AUTO_INCREMENT;