/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servicios.Venta;
import servicios.Reportes;
import servicios.Ventana;
import sistema.Sistema;

/**
 *
 * @author edwin
 */
public class Carrito extends javax.swing.JDialog implements Ventana{
    
    //variables de movimiento de ventanas
    int x, y;

    public DatosFactura getFacturacion() {
        return facturacion;
    }

    public void setFacturacion(DatosFactura facturacion) {
        this.facturacion = facturacion;
    }

    /**
     * @return the readyAdd
     */
    public boolean isReadyAdd() {
        return readyAdd;
    }

    /**
     * @param readyAdd the readyAdd to set
     */
    public void setReadyAdd(boolean readyAdd) {
        this.readyAdd = readyAdd;
    }

    /**
     * @return the edit
     */
    public boolean isEdit() {
        return edit;
    }

    /**
     * @param edit the edit to set
     */
    public void setEdit(boolean edit) {
        this.edit = edit;
    }

    private boolean add;

    private boolean edit;
    private boolean readyAdd;
    public Venta venta;
    private DatosFactura facturacion;
    
    public Carrito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        venta = Sistema.getFactory().venta();
        initComponents();
        this.setLocationRelativeTo(null);
        venta.cargarDatos(LblTotal, Resultados);
        setFacturacion(Sistema.getFactory().facturacion(null, true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopMenu = new javax.swing.JPopupMenu();
        elimnarItem = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BtnCancelar = new javax.swing.JButton();
        BtnFacturar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        TxtId = new javax.swing.JTextField();
        TxtProducto = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTable();
        LblTotal = new javax.swing.JLabel();

        elimnarItem.setText("Eliminar Producto");
        elimnarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elimnarItemMousePressed(evt);
            }
        });
        PopMenu.add(elimnarItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(3, 19, 27));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/carritoCompra.png"))); // NOI18N
        jLabel1.setText("CARRITO DE COMPRA");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 240, -1));

        jPanel6.setBackground(new java.awt.Color(3, 19, 27));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar.setBackground(new java.awt.Color(153, 0, 0));
        BtnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("CERRAR");
        BtnCancelar.setBorder(null);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setFocusPainted(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel6.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 60, 20));

        BtnFacturar.setBackground(new java.awt.Color(0, 102, 0));
        BtnFacturar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        BtnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/facturar.png"))); // NOI18N
        BtnFacturar.setText("FACTURAR");
        BtnFacturar.setToolTipText("Facturar los articulos agregados");
        BtnFacturar.setBorder(null);
        BtnFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnFacturar.setFocusPainted(false);
        BtnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacturarActionPerformed(evt);
            }
        });
        jPanel6.add(BtnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, 20));

        BtnLimpiar.setBackground(new java.awt.Color(51, 51, 51));
        BtnLimpiar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/escoba.png"))); // NOI18N
        BtnLimpiar.setText("LIMPIAR");
        BtnLimpiar.setToolTipText("limpiar la tabla de articulos");
        BtnLimpiar.setBorder(null);
        BtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiar.setFocusPainted(false);
        BtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnLimpiarMousePressed(evt);
            }
        });
        jPanel6.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));

        jPanel2.setBackground(new java.awt.Color(35, 48, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCTO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRECIO:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTIDAD:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TxtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        TxtCantidad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TxtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        TxtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCantidadKeyPressed(evt);
            }
        });
        jPanel2.add(TxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 70, 20));

        TxtId.setBackground(new java.awt.Color(255, 255, 255));
        TxtId.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        TxtId.setForeground(new java.awt.Color(0, 0, 0));
        TxtId.setToolTipText("Codigo");
        TxtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtIdKeyPressed(evt);
            }
        });
        jPanel2.add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 20));

        TxtProducto.setBackground(new java.awt.Color(255, 255, 255));
        TxtProducto.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TxtProducto.setForeground(new java.awt.Color(0, 0, 0));
        TxtProducto.setToolTipText("Nombre de producto");
        TxtProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(TxtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 200, 20));

        TxtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        TxtPrecio.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        TxtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        TxtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 70, 20));

        Resultados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Resultados.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Resultados.setComponentPopupMenu(PopMenu);
        Resultados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Resultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Resultados);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 280));

        LblTotal.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        LblTotal.setForeground(new java.awt.Color(255, 255, 255));
        LblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblTotal.setText("0000000");
        LblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(LblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 460, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(400, 400, 400)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void TxtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           
           if(!isAdd()){
               try {
                    
                    String consulta = this.TxtId.getText();

                    ResultSet rs = venta.buscarItem(consulta);

                    if(rs.first()){
                        rs.beforeFirst();
                        while(rs.next()){
                         this.TxtProducto.setText(rs.getString(2));
                         this.TxtPrecio.setText(rs.getString(3));
                         this.TxtCantidad.setText("1");
                        }
                        this.setAdd(true);
                        this.TxtCantidad.requestFocus();
                    }else{
                        this.setAdd(false);
                        JOptionPane.showMessageDialog(this, "No se encontró ninguna coincidencia");
                        limpiar("");
                    }

               
                } catch (SQLException ex) {
                    this.setAdd(false);
                    JOptionPane.showMessageDialog(this, "No se encontró ninguna coincidencia");
                    Logger.getLogger(Carrito.class.getName()).log(Level.SEVERE, null, ex);
                }
           }else{
               
               venta.insertarItem(this.TxtId.getText(), this.TxtProducto.getText(),
                       Double.valueOf(this.TxtPrecio.getText()), Integer.valueOf(this.TxtCantidad.getText()));
               this.setAdd(false);
               limpiar("");
               this.TxtId.requestFocus();
               // cargarDatos();
               venta.cargarDatos(LblTotal, Resultados);
               
            }

       }else if (evt.getKeyCode() == KeyEvent.VK_BACKSPACE) {
            limpiar("");
            this.setAdd(false);
        }
    }//GEN-LAST:event_TxtIdKeyPressed

    private void TxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantidadKeyPressed
        if(!this.TxtCantidad.equals("") && isAdd()){
          if(evt.getKeyCode() == KeyEvent.VK_ENTER){
              venta.insertarItem(this.TxtId.getText(), this.TxtProducto.getText(),
                      Double.valueOf(this.TxtPrecio.getText()), Integer.valueOf(this.TxtCantidad.getText()));
              this.add = false;
              limpiar("");
              this.TxtId.requestFocus();
              //cargarDatos();
              venta.cargarDatos(LblTotal, Resultados);
              enableOrDisable(true);      
                   
          } 
       }else{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){   
               venta.actualizarItem(Integer.valueOf(this.TxtCantidad.getText()), this.TxtId.getText());
               this.setAdd(false);
               limpiar("");
               this.TxtId.requestFocus();
              // cargarDatos();
              venta.cargarDatos(LblTotal, Resultados);
               enableOrDisable(true);
 
          }
        }
    }//GEN-LAST:event_TxtCantidadKeyPressed

    private void ResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultadosMouseClicked
        int fila = this.Resultados.rowAtPoint(evt.getPoint());
        if(fila > -1){
            this.TxtId.setText(String.valueOf(this.Resultados.getValueAt(fila, 0)));
            this.TxtProducto.setText(String.valueOf(this.Resultados.getValueAt(fila, 1)));
            this.TxtPrecio.setText(String.valueOf(this.Resultados.getValueAt(fila, 2)));
            this.TxtCantidad.setText(String.valueOf(this.Resultados.getValueAt(fila, 3)));
            enableOrDisable(false);
            setEdit(true);
            this.TxtCantidad.requestFocus();
        }
    }//GEN-LAST:event_ResultadosMouseClicked

    private void BtnLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarMousePressed
        venta.vaciarCarrito();
        //cargarDatos();
        venta.cargarDatos(LblTotal, Resultados);
    }//GEN-LAST:event_BtnLimpiarMousePressed

    private void BtnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacturarActionPerformed
        
        getFacturacion().setLocationRelativeTo(null);
        getFacturacion().setVisible(true);
        venta.limpiarTabla(Resultados);

    }//GEN-LAST:event_BtnFacturarActionPerformed

    private void elimnarItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimnarItemMousePressed
        limpiar("");
        int fila = this.Resultados.getSelectedRow();
        String id = (String) this.Resultados.getValueAt(fila, 0);
        venta.borrarItem(Resultados, id);
        this.setAdd(false);
        //cargarDatos();
        venta.cargarDatos(LblTotal, Resultados);
        this.TxtId.requestFocus();
        enableOrDisable(true);
        
    }//GEN-LAST:event_elimnarItemMousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
       this.setLocation(this.getLocation().x + evt.getX()- x , this.getLocation().y + evt.getY() - y );
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

        /**
     * @return the add
     */
    public boolean isAdd() {
        return add;
    }

    /**
     * @param add the add to set
     */
    public void setAdd(boolean add) {
        this.add = add;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Carrito dialog = new Carrito(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnFacturar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JPopupMenu PopMenu;
    private javax.swing.JTable Resultados;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField TxtProducto;
    private javax.swing.JMenuItem elimnarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar(String lugar) {
        this.TxtCantidad.setText("");
        this.TxtId.setText("");
        this.TxtPrecio.setText("");
        this.TxtProducto.setText("");
        this.TxtId.requestFocus();
    }
    
    
    private void enableOrDisable(boolean type){
        if(type){
            this.TxtId.enable();
            this.TxtCantidad.enable();
            this.TxtPrecio.enable();
            this.TxtProducto.enable();
        }
        else{
            this.TxtPrecio.disable();
            this.TxtId.disable();
            this.TxtProducto.disable();
        }
    }
}
