/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.ImageIcon;
import javax.swing.text.DefaultCaret;
import sistema.Sistema;

/**
 *
 * @author edwin
 */
public class MensajePlantilla extends javax.swing.JDialog {

    private ImageIcon icon;
    
    public MensajePlantilla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.icono.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnCancelar1 = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        txtTipoMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 48, 54));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(3, 19, 27));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar1.setBackground(new java.awt.Color(153, 0, 0));
        BtnCancelar1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar1.setText("CERRAR");
        BtnCancelar1.setToolTipText("cerrar");
        BtnCancelar1.setBorder(null);
        BtnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar1.setFocusPainted(false);
        BtnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelar1ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 60, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 370, 40));

        icono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        icono.setForeground(new java.awt.Color(255, 255, 255));
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/advertencia.png"))); // NOI18N
        icono.setFocusable(false);
        icono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icono.setIconTextGap(-10);
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 40));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(35, 48, 54));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Mensaje  -->");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 290, -1));

        jPanel3.setBackground(new java.awt.Color(3, 19, 27));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipoMensaje.setBackground(new java.awt.Color(3, 19, 27));
        txtTipoMensaje.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtTipoMensaje.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoMensaje.setText("TIPO DE MENSAJE");
        jPanel3.add(txtTipoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelar1ActionPerformed

    
    public void mensaje(String tipo, String mensaje, String titulo){
        this.txtTipoMensaje.setText(titulo.toUpperCase());
        this.jTextArea1.setText(mensaje);
        
        switch(tipo.toLowerCase()){
            case "advertencia":
                setIcon(Sistema.getFactory().icono(getClass().getClassLoader().getResource("Recursos/imagenes/advertencia.png")));
                this.icono.setIcon(getIcon());
                break;
            case "error":
                setIcon(Sistema.getFactory().icono(getClass().getResource("/Recursos/imagenes/error.png")));
                this.icono.setIcon(getIcon());
                break;
            case "exito":
                setIcon(Sistema.getFactory().icono(getClass().getResource("/Recursos/imagenes/exito.png")));
                this.icono.setIcon(getIcon());
                break;
            default:
                setIcon(Sistema.getFactory().icono(getClass().getResource("/Recursos/imagenes/ayuda.png")));
                this.icono.setIcon(getIcon());
                break;
        }
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.icono.repaint();
    }

    public ImageIcon getIcon() {
        return icon;
    }

    public void setIcon(ImageIcon icon) {
        this.icon = icon;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajePlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajePlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajePlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajePlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MensajePlantilla dialog = new MensajePlantilla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar1;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel txtTipoMensaje;
    // End of variables declaration//GEN-END:variables
}
