/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author edwin
 */
public class Opciones_usuarios extends javax.swing.JDialog {

    ///variables para mover ventana
    int x,y;
    
    public Opciones_usuarios(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnAGREGARU = new javax.swing.JButton();
        BtnMODIFICARU = new javax.swing.JButton();
        BtnELIMINARU = new javax.swing.JButton();
        BtnLISTARU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 19, 27));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/usuariosPeque.png"))); // NOI18N
        jLabel1.setText("OPCIONES DE USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        jPanel2.setBackground(new java.awt.Color(3, 19, 27));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar.setBackground(new java.awt.Color(153, 0, 0));
        BtnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setText("CERRAR");
        BtnCancelar.setBorder(null);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setFocusPainted(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 60, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 580, 40));

        jPanel3.setBackground(new java.awt.Color(35, 48, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿QUE DESEA HACER?");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, -1));

        BtnAGREGARU.setBackground(new java.awt.Color(0, 102, 0));
        BtnAGREGARU.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnAGREGARU.setForeground(new java.awt.Color(255, 255, 255));
        BtnAGREGARU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/addPequeño.png"))); // NOI18N
        BtnAGREGARU.setText("AGREGAR USUARIOS");
        BtnAGREGARU.setActionCommand("");
        BtnAGREGARU.setBorder(null);
        BtnAGREGARU.setBorderPainted(false);
        BtnAGREGARU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAGREGARU.setFocusPainted(false);
        BtnAGREGARU.setIconTextGap(10);
        BtnAGREGARU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/add.png"))); // NOI18N
        BtnAGREGARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAGREGARUActionPerformed(evt);
            }
        });
        jPanel3.add(BtnAGREGARU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 180, 90));

        BtnMODIFICARU.setBackground(new java.awt.Color(0, 102, 102));
        BtnMODIFICARU.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnMODIFICARU.setForeground(new java.awt.Color(255, 255, 255));
        BtnMODIFICARU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/ediPequenho.png"))); // NOI18N
        BtnMODIFICARU.setText("MODIFICAR USUARIOS");
        BtnMODIFICARU.setBorder(null);
        BtnMODIFICARU.setBorderPainted(false);
        BtnMODIFICARU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMODIFICARU.setFocusPainted(false);
        BtnMODIFICARU.setIconTextGap(10);
        BtnMODIFICARU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/edi.png"))); // NOI18N
        BtnMODIFICARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMODIFICARUActionPerformed(evt);
            }
        });
        jPanel3.add(BtnMODIFICARU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 180, 90));

        BtnELIMINARU.setBackground(new java.awt.Color(153, 0, 0));
        BtnELIMINARU.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnELIMINARU.setForeground(new java.awt.Color(255, 255, 255));
        BtnELIMINARU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/delPequenho.png"))); // NOI18N
        BtnELIMINARU.setText("ELIMINAR USUARIOS");
        BtnELIMINARU.setBorder(null);
        BtnELIMINARU.setBorderPainted(false);
        BtnELIMINARU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnELIMINARU.setFocusPainted(false);
        BtnELIMINARU.setIconTextGap(10);
        BtnELIMINARU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/del.png"))); // NOI18N
        BtnELIMINARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnELIMINARUActionPerformed(evt);
            }
        });
        jPanel3.add(BtnELIMINARU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 180, 90));

        BtnLISTARU.setBackground(new java.awt.Color(0, 0, 0));
        BtnLISTARU.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        BtnLISTARU.setForeground(new java.awt.Color(255, 255, 255));
        BtnLISTARU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/listarPequenho.png"))); // NOI18N
        BtnLISTARU.setText("LISTAR USUARIOS");
        BtnLISTARU.setBorder(null);
        BtnLISTARU.setBorderPainted(false);
        BtnLISTARU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLISTARU.setFocusPainted(false);
        BtnLISTARU.setIconTextGap(10);
        BtnLISTARU.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/listar.png"))); // NOI18N
        jPanel3.add(BtnLISTARU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 580, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnAGREGARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAGREGARUActionPerformed
        //this.dispose();
        AgregarUsuarios AgregarU = new AgregarUsuarios(new javax.swing.JDialog(),true);
        AgregarU.setVisible(true);
    }//GEN-LAST:event_BtnAGREGARUActionPerformed

    private void BtnMODIFICARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMODIFICARUActionPerformed
        //this.dispose();
        ModificarUsuarios ModificarU = new ModificarUsuarios(new javax.swing.JDialog(),true);
        ModificarU.setVisible(true);
    }//GEN-LAST:event_BtnMODIFICARUActionPerformed

    private void BtnELIMINARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnELIMINARUActionPerformed
        EliminarUsuario EliminarU = new EliminarUsuario (new javax.swing.JDialog(),true);
        EliminarU.setVisible(true);
    }//GEN-LAST:event_BtnELIMINARUActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(this.getLocation().x + evt.getX()- x , this.getLocation().y + evt.getY() - y );
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Opciones_usuarios dialog = new Opciones_usuarios(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAGREGARU;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnELIMINARU;
    private javax.swing.JButton BtnLISTARU;
    private javax.swing.JButton BtnMODIFICARU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
